sudo: false

addons:
  apt:
    packages:
    - ca-certificates
    - libcurl4-openssl-dev

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --version
  - bundle exec htmlproofer --timeframe 4w --assume-extension --check-favicon --check-html --check-img-http ./_site/ --url-swap "https?\:\/\/(localhost\:4000|www\.tockos\.org):"

